<a href="https://colab.research.google.com/github/Nayidtq/CV/blob/main/Chapter3_from_the_BookNQ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports and Load the data

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
# %matplotlib inline

In [ ]:
df = pd.read_csv("https://github.com/fenago/datasets/raw/main/SMSSpamCollection.txt", sep ='\t', names=['label', 'message'])
df.head()


# for classification in an AI Model for NLP - it requires a label and a text column
# if your dataset has multiple columns - then drop the columns that are not text based

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
len(df)

5572

In [ ]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [ ]:
df['message'].unique()

array(['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
       'Ok lar... Joking wif u oni...',
       "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       ..., 'Pity, * was in mood for that. So...any other suggestions?',
       "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free",
       'Rofl. Its true to its name'], dtype=object)

In [ ]:
df['message'].value_counts()

message
Sorry, I'll call later                                                                                                                                         30
I cant pick the phone right now. Pls send a message                                                                                                            12
Ok...                                                                                                                                                          10
Okie                                                                                                                                                            4
Your opinion about me? 1. Over 2. Jada 3. Kusruthi 4. Lovable 5. Silent 6. Spl character 7. Not matured 8. Stylish 9. Simple Pls reply..                        4
                                                                                                                                                               ..
No. On the way home. So if not for the long dry spell the season would have been over                                                                           1
Urgent! Please call 09061743811 from landline. Your ABTA complimentary 4* Tenerife Holiday or £5000 cash await collection SAE T&Cs Box 326 CW25WX 150ppm        1
Dear 0776xxxxxxx U've been invited to XCHAT. This is our final attempt to contact u! Txt CHAT to 86688 150p/MsgrcvdHG/Suite342/2Lands/Row/W1J6HL LDN 18yrs      1
I think asking for a gym is the excuse for lazy people. I jog.                                                                                                  1
Rofl. Its true to its name                                                                                                                                      1
Name: count, Length: 5169, dtype: int64

# Clean the data

In [ ]:
# This is the minimum.  You can obviously clean the data more than this if you choose.
# I would consider using Lemma's... but it is your choice

import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['message'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
corpus[:5]

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though']

# Train Test Split

In [ ]:
X = df['message']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

X_train.shape

(3900,)

# Transform the text into Vectors (numbers)

In [ ]:
# CountVectorizer: Converts the text in a matrix of token counts... creates the Bag of Words (BoW) - the count of each word
# TfidfTransformer: Coverting those counts (from the BoW) - into a score for each word.  So each word is represented by a number.

from sklearn.feature_extraction.text import CountVectorizer
count_vect=CountVectorizer()
X_train_counts =count_vect.fit_transform(X_train)

print("Shape of count vectorizer", X_train_counts.shape)

from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf =tfidf_transformer.fit_transform(X_train_counts)

print("Shape of tfidf feature extraction",X_train_tfidf.shape)

Shape of count vectorizer (3900, 7263)
Shape of tfidf feature extraction (3900, 7263)

# The Data is now primed... we simply need to put the data into an Algorithm and create a model

In [ ]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(solver='lbfgs')
clf.fit(X_train_tfidf, y_train)

LogisticRegression()

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LogisticRegression()),])
text_clf.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LogisticRegression())])

In [ ]:
predictions = text_clf.predict(X_test)

In [ ]:
from sklearn import metrics
print("Confusion Metrics\n",metrics.confusion_matrix(y_test,predictions), end="\n\n\n")

print("Classification Report\n",metrics.classification_report(y_test,predictions), end="\n\n\n")

print("Accuracy Score:", metrics.accuracy_score(y_test,predictions))

Confusion Metrics
 [[1446    2]
 [  45  179]]


Classification Report
               precision    recall  f1-score   support

         ham       0.97      1.00      0.98      1448
        spam       0.99      0.80      0.88       224

    accuracy                           0.97      1672
   macro avg       0.98      0.90      0.93      1672
weighted avg       0.97      0.97      0.97      1672



Accuracy Score: 0.97188995215311

In [ ]:
def predict_text(model, text):
    """
    Predict the class of the given text using the trained model.

    :param model: The trained text classification model (pipeline).
    :param text: A string containing the text to be classified.
    :return: The predicted class of the text.
    """
    prediction = model.predict([text])
    return prediction[0]

# Example usage
your_text = "Your sample text here"
prediction = predict_text(text_clf, your_text)
print("Predicted class:", prediction)

Predicted class: spam

In [ ]:
def predict_text_with_score(model, text):
    """
    Predict the class of the given text using the trained model and provide the probability scores.

    :param model: The trained text classification model (pipeline).
    :param text: A string containing the text to be classified.
    :return: The predicted class of the text and the probability scores.
    """
    prediction = model.predict([text])
    prediction_proba = model.predict_proba([text])

    # Getting the class labels
    class_labels = model.classes_

    # Formatting the probability scores along with the class labels
    proba_scores = {class_labels[i]: prediction_proba[0][i] for i in range(len(class_labels))}

    return prediction[0], proba_scores

# Example usage
your_text = "Your sample text here"
predicted_class, scores = predict_text_with_score(text_clf, your_text)
print("Predicted class:", predicted_class)
print("Probability Scores:", scores)

Predicted class: spam
Probability Scores: {'ham': 0.4575389633637499, 'spam': 0.5424610366362501}

In [ ]:
import joblib

# Save your model
joblib.dump(text_clf, 'text_clf_model.joblib')

['text_clf_model.joblib']

In [ ]:
from sklearn.svm import SVC
lr_model = SVC(gamma='auto')


SVC_text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', SVC(gamma='auto')),])
SVC_text_clf.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', SVC(gamma='auto'))])

In [ ]:
SVC_predictions = SVC_text_clf.predict(X_test)

In [ ]:
from sklearn import metrics
print("Confusion Metrics\n",metrics.confusion_matrix(y_test,SVC_predictions), end="\n\n\n")

print("Classification Report\n",metrics.classification_report(y_test,SVC_predictions), end="\n\n\n")

print("Accuracy Score:", metrics.accuracy_score(y_test,SVC_predictions))

Confusion Metrics
 [[1448    0]
 [ 224    0]]


Classification Report
               precision    recall  f1-score   support

         ham       0.87      1.00      0.93      1448
        spam       0.00      0.00      0.00       224

    accuracy                           0.87      1672
   macro avg       0.43      0.50      0.46      1672
weighted avg       0.75      0.87      0.80      1672



Accuracy Score: 0.8660287081339713

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
y_train.value_counts()

label
ham     3377
spam     523
Name: count, dtype: int64

In [ ]:
y_test.value_counts()

label
ham     1448
spam     224
Name: count, dtype: int64

# Let's try this again with a new dataset

In [8]:
!pip install requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
import requests

url = "https://raw.githubusercontent.com/kolaveridi/kaggle-sentiment-analysis/master/datasets/train.ft.txt"
try:
    response = requests.get(url)
    response.raise_for_status()  # Raise an exception for bad status codes (404, 500, etc.)

    # If the request is successful, read the data into pandas
    df = pd.read_csv(
        io.StringIO(response.text), # Use io.StringIO to treat the text as a file
        header=None,
        sep='\t',
        names=["label", "message"],
        converters={'label': lambda x: x.replace('__label__', '')}
    )
    print("Data loaded successfully")
    print(df.head())

except requests.exceptions.RequestException as e:
    print(f"Error fetching data: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests) (2025.1.31)
Error fetching data: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/kolaveridi/kaggle-sentiment-analysis/master/datasets/train.ft.txt

In [9]:
df.sample(10)

,,label,message
8488,NBA2K,Positive,of JUST WANNA THANK RhandlerR RhandlerR Rhandl...
4214,CS-GO,Irrelevant,Best Gun Player in CS: GO?..
9505,Overwatch,Positive,Well overwatch It got lit
4908,GrandTheftAuto(GTA),Positive,Five Very best GTA Video games You Can Play In...
4549,Google,Positive,Congrats guys.
10112,PlayerUnknownsBattlegrounds(PUBG),Irrelevant,xboxaimbot.com is the greatest place to colle...
7734,MaddenNFL,Negative,Can’t fix franchise but has enough revenue to ...
12840,Xbox(Xseries),Negative,"I don ’ t want a ps5 string or any xbox x / s,..."
4101,CS-GO,Irrelevant,com ITS GRAND FINALS DAY! . . THE WINNER OF TH...
2322,CallOfDuty,Negative,"I have a £140 headset, but I can't hear anyone..."

In [10]:
df.label.value_counts()

label
Negative      22542
Positive      20832
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

In [11]:
df = df[df['label'].isin(['Positive', 'Negative'])]
df.label.value_counts()

label
Negative    22542
Positive    20832
Name: count, dtype: int64

In [15]:
len(df)

43013

In [17]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [18]:
df = df.dropna(subset=["message"])
df.isnull().sum()

label      0
message    0
dtype: int64

In [19]:
df.label.value_counts()

label
Negative    22358
Positive    20655
Name: count, dtype: int64

In [21]:
df['message'].unique()

array(['im getting on borderlands and i will murder you all ,',
       'I am coming to the borders and I will kill you all,',
       'im getting on borderlands and i will kill you all,', ...,
       'Just realized the windows partition of my Mac is now 6 years behind on Nvidia drivers and I have no idea how he didn’t notice',
       'Just realized between the windows partition of my Mac is like being 6 years behind on Nvidia drivers and cars I have no fucking idea how I ever didn ’ t notice',
       'Just like the windows partition of my Mac is like 6 years behind on its drivers So you have no idea how I didn’t notice'],
      dtype=object)

In [22]:
df['message'].value_counts()

message
At the same time, despite the fact that there are currently some 100 million people living below the poverty line, most of them do not have access to health services and do not have access to health care, while most of them do not have access to health care.    82
                                                                                                                                                                                                                                                                      82
It is not the first time that the EU Commission has taken such a step.                                                                                                                                                                                                82
<unk>                                                                                                                                                                                                                                                                 77
Wow                                                                                                                                                                                                                                                                   48
                                                                                                                                                                                                                                                                      ..
How Ubisoft is announcing the new Assassin's Creed right now is right strange, but it makes me excited                                                                                                                                                                 1
The way Ubisoft is announcing this new Assassin’s Creed right now is proper weird but it’s getting people excited                                                                                                                                                      1
The way down Ubisoft is announcing that the new Assassin ’ s Creed outfit right now is proper... weird but it ’ s getting me all excited                                                                                                                               1
The way Ubisoft keeps announcing the new Assassin’s Unity system now is proper weird but it’s keeping me excited                                                                                                                                                       1
Just like the windows partition of my Mac is like 6 years behind on its drivers So you have no idea how I didn’t notice                                                                                                                                                1
Name: count, Length: 40287, dtype: int64

In [23]:
df.head(15)

                     label                                            message
2401 Borderlands  Positive  im getting on borderlands and i will murder yo...
     Borderlands  Positive  I am coming to the borders and I will kill you...
     Borderlands  Positive  im getting on borderlands and i will kill you ...
     Borderlands  Positive  im coming on borderlands and i will murder you...
     Borderlands  Positive  im getting on borderlands 2 and i will murder ...
     Borderlands  Positive  im getting into borderlands and i can murder y...
2402 Borderlands  Positive  So I spent a few hours making something for fu...
     Borderlands  Positive  So I spent a couple of hours doing something f...
     Borderlands  Positive  So I spent a few hours doing something for fun...
     Borderlands  Positive  So I spent a few hours making something for fu...
     Borderlands  Positive  2010 So I spent a few hours making something f...
     Borderlands  Positive                                                was
2404 Borderlands  Positive  that was the first borderlands session in a lo...
     Borderlands  Positive  this was the first Borderlands session in a lo...
     Borderlands  Positive  that was the first borderlands session in a lo...

In [24]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
# Instead of iterating using an index, iterate through each row of the dataframe
for index, row in df.iterrows():
    review = re.sub('[^a-zA-Z]', ' ', row['message'])  # Access message from the row
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [25]:
corpus[:5]

['im get borderland murder',
 'come border kill',
 'im get borderland kill',
 'im come borderland murder',
 'im get borderland murder']

In [27]:
X = df['message']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

X_train.shape

(30109,)

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect=CountVectorizer()
X_train_counts =count_vect.fit_transform(X_train)

print("Shape of count vectorizer", X_train_counts.shape)

from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf =tfidf_transformer.fit_transform(X_train_counts)

print("Shape of tfidf feature extraction",X_train_tfidf.shape)

Shape of count vectorizer (30109, 17952)
Shape of tfidf feature extraction (30109, 17952)

In [29]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(solver='lbfgs')
clf.fit(X_train_tfidf, y_train)

LogisticRegression()

In [30]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LogisticRegression()),])
text_clf.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LogisticRegression())])

In [31]:
predictions = text_clf.predict(X_test)

In [32]:
from sklearn import metrics
print("Confusion Metrics\n",metrics.confusion_matrix(y_test,predictions), end="\n\n\n")

print("Classification Report\n",metrics.classification_report(y_test,predictions), end="\n\n\n")

print("Accuracy Score:", metrics.accuracy_score(y_test,predictions))

Confusion Metrics
 [[5991  670]
 [ 803 5440]]


Classification Report
               precision    recall  f1-score   support

    Negative       0.88      0.90      0.89      6661
    Positive       0.89      0.87      0.88      6243

    accuracy                           0.89     12904
   macro avg       0.89      0.89      0.89     12904
weighted avg       0.89      0.89      0.89     12904



Accuracy Score: 0.8858493490390577

In [33]:
!pip install -q -U google-genai

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.7/137.7 kB 6.1 MB/s eta 0:00:00

In [34]:
from google import genai

client = genai.Client(api_key="AIzaSyA4-TRjvRTpOxHHiKVBkFzMcRX3FMwQFf0")
response = client.models.generate_content(
    model="gemini-2.0-flash", contents="Explain how AI works"
)
print(response.text)

Alright, let's break down how AI works. It's a broad field, so I'll cover the core concepts and some popular techniques.  Think of it as a high-level overview, with pointers to dive deeper if you're interested.

**What is AI, at its Core?**

At its simplest, Artificial Intelligence (AI) is about creating machines that can perform tasks that typically require human intelligence.  This includes things like:

*   **Learning:** Improving performance based on experience.
*   **Reasoning:**  Using logic and rules to solve problems.
*   **Problem-Solving:**  Finding solutions to complex issues.
*   **Perception:** Understanding sensory input (like images, sound, text).
*   **Natural Language Understanding:**  Understanding and generating human language.

**The Basic Building Blocks**

1.  **Data:** AI thrives on data.  The more data an AI system has access to, the better it can learn and perform. This data can be in many forms: text, images, numbers, audio, etc.

2.  **Algorithms:** These are the instructions or recipes that tell the AI system how to process the data.  Algorithms determine how the AI learns, makes decisions, and solves problems.

3.  **Models:**  A model is a representation of what the AI has learned from the data and algorithms.  It's the "brain" of the AI system, allowing it to make predictions or take actions based on new input.

4.  **Computation:** AI, especially modern AI, often requires significant computing power.  This is why advancements in hardware (like GPUs) have been crucial for AI development.

**Key Approaches to AI**

Here are some of the major approaches used in AI:

*   **Machine Learning (ML):**  This is the most popular and rapidly evolving area of AI. Instead of explicitly programming a machine to do something, you *train* it on data.

    *   **Supervised Learning:** You give the AI labeled data, meaning the data has the correct answer or outcome associated with it.  The AI learns to map the input data to the correct output.  Examples:
        *   **Image Classification:** Training an AI to identify cats vs. dogs, where you provide images of cats and dogs and tell the AI which is which.
        *   **Spam Detection:** Training an AI to identify spam emails based on examples of spam and non-spam emails.
        *   **Regression:** Predicting a continuous value (e.g., predicting house prices based on features like size, location, etc.).
    *   **Unsupervised Learning:** You give the AI unlabeled data and ask it to find patterns or structure in the data. Examples:
        *   **Clustering:** Grouping customers into segments based on their purchasing behavior.
        *   **Anomaly Detection:** Identifying unusual transactions that might be fraudulent.
        *   **Dimensionality Reduction:** Reducing the number of variables in a dataset while preserving important information.
    *   **Reinforcement Learning:** The AI learns by interacting with an environment and receiving rewards or penalties for its actions.  The goal is to maximize the reward over time.  Examples:
        *   **Training an AI to play games:** The AI learns by trial and error, receiving rewards for winning and penalties for losing.
        *   **Robotics:** Training a robot to navigate a maze or perform a task.

*   **Deep Learning (DL):** A subfield of machine learning that uses artificial neural networks with multiple layers (hence "deep") to analyze data.  Deep learning is particularly good at handling complex data like images, audio, and text.

    *   **Neural Networks:** Inspired by the structure of the human brain, neural networks consist of interconnected nodes (neurons) that process and transmit information.
    *   **Convolutional Neural Networks (CNNs):**  Excellent for image recognition and computer vision tasks.  They use convolutional layers to extract features from images.
    *   **Recurrent Neural Networks (RNNs):**  Designed for processing sequential data like text and time series data.  They have feedback loops that allow them to remember past information.
    *   **Transformers:** A more recent architecture that has revolutionized natural language processing. They use attention mechanisms to weigh the importance of different parts of the input sequence.  Think ChatGPT!

*   **Rule-Based Systems (Expert Systems):** These systems use a set of pre-defined rules to make decisions.  They are useful for situations where the rules are well-defined and the problem is relatively simple.

    *   **IF-THEN Rules:** The core of the system.  "IF the temperature is above 90 degrees THEN turn on the AC."
    *   **Knowledge Base:**  A repository of facts and rules about a specific domain.

*   **Natural Language Processing (NLP):** This focuses on enabling computers to understand, interpret, and generate human language.

    *   **Text Classification:** Categorizing text into different categories (e.g., sentiment analysis, topic classification).
    *   **Machine Translation:** Translating text from one language to another.
    *   **Text Summarization:** Creating a concise summary of a longer text.
    *   **Question Answering:** Answering questions based on a given text or knowledge base.
    *   **Chatbots:**  Developing conversational agents that can interact with humans in natural language.

*   **Computer Vision:** This area focuses on enabling computers to "see" and interpret images and videos.

    *   **Object Detection:** Identifying and locating objects in an image.
    *   **Image Segmentation:** Dividing an image into different regions based on their characteristics.
    *   **Image Recognition:** Identifying the content of an image (e.g., recognizing a specific person or object).

**How the Learning Process Works (Simplified)**

Let's take Supervised Learning as an example:

1.  **Data Collection:** Gather a large dataset of labeled examples.  For example, images of cats and dogs, labeled as "cat" or "dog."

2.  **Model Selection:** Choose an appropriate machine learning model (e.g., a Convolutional Neural Network for image classification).

3.  **Training:** Feed the data to the model. The model adjusts its internal parameters (weights and biases) to learn the relationship between the input data and the labels.  This is done through an iterative process of:
    *   **Forward Pass:** The model makes a prediction based on the input data.
    *   **Loss Calculation:**  The model calculates how wrong its prediction was (the "loss").
    *   **Backpropagation:** The model uses the loss to adjust its parameters to improve its predictions.

4.  **Validation:** Use a separate dataset (the validation set) to evaluate the model's performance and fine-tune its parameters.  This helps to prevent overfitting (where the model learns the training data too well and performs poorly on new data).

5.  **Testing:**  Once the model is trained and validated, use a final, unseen dataset (the test set) to assess its performance on new data.

6.  **Deployment:** Deploy the trained model into a real-world application.

**Important Considerations**

*   **Bias:** AI models can inherit biases present in the data they are trained on. This can lead to unfair or discriminatory outcomes.  It's crucial to address bias in data and algorithms.
*   **Explainability:**  Understanding why an AI model makes a particular decision can be challenging, especially with deep learning models.  Explainable AI (XAI) is a growing field that aims to make AI models more transparent and understandable.
*   **Ethics:**  AI raises ethical concerns about privacy, security, job displacement, and the potential for misuse.  Responsible AI development is essential.
*   **Data Quality:**  "Garbage in, garbage out."  The quality of the data used to train an AI model is critical to its performance.

**In Summary**

AI is a complex field with many different approaches and techniques. The core principles involve using data, algorithms, and models to enable machines to perform tasks that typically require human intelligence. Machine learning, particularly deep learning, has been a major driver of recent advances in AI. However, it's important to be aware of the ethical considerations and potential biases associated with AI development and deployment.

This is just a starting point.  If you want to delve deeper, I recommend exploring specific areas of AI that interest you and looking into online courses, tutorials, and research papers. Good luck!

**ASSIGNMENT** **4**

First, I'll install the necessary libraries and download the dataset.

In [46]:
!pip install requests
!pip install -U scikit-learn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.pipeline import Pipeline
import joblib
import io
import requests

nltk.download('stopwords')

Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests) (2025.1.31)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.5.0)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

**Step 2: Load the Dataset**

In [47]:
try:
    url = "https://raw.githubusercontent.com/kolaveridi/kaggle-sentiment-analysis/master/datasets/train.ft.txt"
    response = requests.get(url)
    response.raise_for_status()  # Raise an exception for bad status codes (404, 500, etc.)

    # If the request is successful, read the data into pandas
    df = pd.read_csv(
        io.StringIO(response.text), # Use io.StringIO to treat the text as a file
        header=None,
        sep='\t',
        names=["label", "message"],
        converters={'label': lambda x: x.replace('__label__', '')}
    )
    print("Data loaded successfully")
    print(df.head())

except requests.exceptions.RequestException as e:
    print(f"Error fetching data: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

Error fetching data: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/kolaveridi/kaggle-sentiment-analysis/master/datasets/train.ft.txt

**Step 3: Data Cleaning**

In [48]:
# Map sentiment labels to 'Positive' and 'Negative'
df['label'] = df['label'].replace({'1': 'Positive', '2':'Negative'})
# Data Cleaning
df = df.dropna(subset=["message"])

**Step 4: Text Preprocessing**

In [49]:
# Preprocessing steps
ps = PorterStemmer()
corpus = []
for index, row in df.iterrows():
    review = re.sub('[^a-zA-Z]', ' ', row['message'])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
df['cleaned_message'] = corpus

**Step 5: Train/Test Split**

In [50]:
# Splitting data into training and testing
X = df['cleaned_message']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

**Step 6: Text to Vectors**

In [51]:
# Transform the text into vectors
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

print("Shape of tfidf feature extraction",X_train_tfidf.shape)

Shape of tfidf feature extraction (30109, 12833)

**Step 7: Model Training**

In [52]:
# Create a text classification pipeline using TF-IDF and Logistic Regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', max_iter=1000)
model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

**Step 8: Model Evaluation**

In [53]:
# Evaluate the model and print metrics
# Make predictions
predictions = model.predict(X_test_tfidf)

# Print confusion matrix
print("Confusion Metrics\n", metrics.confusion_matrix(y_test, predictions), end="\n\n\n")

# Print classification report
print("Classification Report\n", metrics.classification_report(y_test, predictions), end="\n\n\n")

# Print accuracy score
print("Accuracy Score:", metrics.accuracy_score(y_test, predictions))

Confusion Metrics
 [[6026  635]
 [ 916 5327]]


Classification Report
               precision    recall  f1-score   support

    Negative       0.87      0.90      0.89      6661
    Positive       0.89      0.85      0.87      6243

    accuracy                           0.88     12904
   macro avg       0.88      0.88      0.88     12904
weighted avg       0.88      0.88      0.88     12904



Accuracy Score: 0.879804711717297

**Step 9: Analysis**

In [54]:
# Analyze the confusion matrix and classification report
print("""
Model Performance Analysis:

Confusion Matrix:
- The confusion matrix displays the counts of true positives, true negatives, false positives, and false negatives.
  - True Positives (Top left): The number of positive reviews correctly predicted as positive.
  - True Negatives (Bottom right): The number of negative reviews correctly predicted as negative.
  - False Positives (Top right): The number of negative reviews incorrectly predicted as positive.
  - False Negatives (Bottom left): The number of positive reviews incorrectly predicted as negative.
  A good model will have high values on the diagonal (True Positives and True Negatives) and low values off the diagonal (False Positives and False Negatives).

Classification Report:
- The classification report provides a detailed analysis of the model's performance for each class (positive and negative):
    - Precision: The ratio of true positives to all predicted positives. High precision means the model makes fewer false positive predictions.
    - Recall: The ratio of true positives to all actual positives. High recall means the model is good at finding most of the positive cases.
    - F1-Score: The harmonic mean of precision and recall. It is a good metric to use when there is an imbalance between the classes.
    - Support: The number of actual occurrences of each class in the test data.

Insights:
- The analysis of the classification report and the confusion matrix gives us an in depth look of the model’s performance.
- A high accuracy suggests that the model does a good job at classifying reviews as positive or negative, but a more balanced f1-score is always the goal, this could be improved with hyperparameter tuning.
- Based on the values in the classification report, check the precision and recall of each class to determine how well the model does on either positive or negative reviews.

Potential Improvements:
- Hyperparameter tuning: Experimenting with different values of model parameters (e.g., C value in Logistic Regression).
- More data: Collecting and using a larger dataset will help the model generalize better.
- Different model: Exploring other classification algorithms (e.g., Random Forest, SVM) or Deep Learning techniques.
- More advanced preprocessing: Using lemmatization, n-grams, or more advanced word embeddings.
- Class imbalance handling: Addressing the imbalance between positive and negative classes if it exists.
""")

Model Performance Analysis:

Confusion Matrix:
- The confusion matrix displays the counts of true positives, true negatives, false positives, and false negatives.
  - True Positives (Top left): The number of positive reviews correctly predicted as positive.
  - True Negatives (Bottom right): The number of negative reviews correctly predicted as negative.
  - False Positives (Top right): The number of negative reviews incorrectly predicted as positive.
  - False Negatives (Bottom left): The number of positive reviews incorrectly predicted as negative.
  A good model will have high values on the diagonal (True Positives and True Negatives) and low values off the diagonal (False Positives and False Negatives).

Classification Report:
- The classification report provides a detailed analysis of the model's performance for each class (positive and negative):
    - Precision: The ratio of true positives to all predicted positives. High precision means the model makes fewer false positive predictions.
    - Recall: The ratio of true positives to all actual positives. High recall means the model is good at finding most of the positive cases.
    - F1-Score: The harmonic mean of precision and recall. It is a good metric to use when there is an imbalance between the classes.
    - Support: The number of actual occurrences of each class in the test data.

Insights:
- The analysis of the classification report and the confusion matrix gives us an in depth look of the model’s performance.
- A high accuracy suggests that the model does a good job at classifying reviews as positive or negative, but a more balanced f1-score is always the goal, this could be improved with hyperparameter tuning.
- Based on the values in the classification report, check the precision and recall of each class to determine how well the model does on either positive or negative reviews.

Potential Improvements:
- Hyperparameter tuning: Experimenting with different values of model parameters (e.g., C value in Logistic Regression).
- More data: Collecting and using a larger dataset will help the model generalize better.
- Different model: Exploring other classification algorithms (e.g., Random Forest, SVM) or Deep Learning techniques.
- More advanced preprocessing: Using lemmatization, n-grams, or more advanced word embeddings.
- Class imbalance handling: Addressing the imbalance between positive and negative classes if it exists.